#!/bin/bash

echo

RPI="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20"

num=$1

for i in [ $RPI ];

do

num=$[num+1]

fping -cl -t300 $device 2>/dev/null 1>/dev/null

if [ "$?" -gt 2 ]

then
	echo "pi$num is alive"
else
	echo "pi$num is dead"
fi

echo

done
